# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-23 11:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('transcoder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcodertask',
            name='downloadURL',
            field=models.CharField(default=datetime.datetime(2016, 4, 23, 11, 39, 52, 277849, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
    ]
