# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-23 11:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transcoder', '0002_transcodertask_downloadurl'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transcodertask',
            old_name='dformate',
            new_name='dformat',
        ),
    ]
