# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-23 12:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('transcoder', '0003_auto_20160423_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcodertask',
            name='transnode',
            field=models.CharField(default=datetime.datetime(2016, 4, 23, 12, 32, 46, 576112, tzinfo=utc), max_length=60),
            preserve_default=False,
        ),
    ]
