# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-24 14:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('transcoder', '0004_transcodertask_transnode'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcodertask',
            name='endtime',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 24, 14, 20, 32, 310892, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transcodertask',
            name='satrttime',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 24, 14, 20, 45, 365954, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
