# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-24 14:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transcoder', '0006_auto_20160424_2232'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transcodertask',
            old_name='satrttime',
            new_name='starttime',
        ),
    ]
