# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-29 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcoder', '0007_auto_20160424_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcodertask',
            name='abitrate',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
