# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-21 08:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcoder', '0008_transcodertask_abitrate'),
    ]

    operations = [
        migrations.CreateModel(
            name='mergetask',
            fields=[
                ('taskid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('createtime', models.DateTimeField()),
                ('src1', models.CharField(max_length=100)),
                ('src2', models.CharField(max_length=100)),
                ('dst', models.CharField(max_length=100)),
                ('status', models.IntegerField()),
            ],
        ),
    ]
